### ISSUE TITLE
is posible to aceppt wildcard for letsencrypt?

### ISSUE THREAD

**Issue by quautla** [Alexander-Krause/rpi-docker-letsencrypt-nginx-proxy-companion#2]
I noticed recently that Letsencrypt accept wildcards, but I don´t know if this version of docker container can be configured via docker-compose.yml like this

```
    environment:
      - LETSENCRYPT_HOST="*.ctoadmin.mx"
      - LETSENCRYPT_EMAIL=xxx@xxx.com
      - PORT=8080
      - VIRTUAL_HOST="*.ctoadmin.mx"
    networks:
      - reverse-proxy
    restart: always
```
instead of:

```
LETSENCRYPT_HOST=portal1.mydomain.com,portal2.mydomain.com,portal3.mydomain.com
VIRTUAL_HOST=portal1.mydomain.com,portal2.mydomain.com,portal3.mydomain.com
```

And the second question where could I obtain the value for te TXT record:
```
Please deploy a DNS TXT record under the name
_acme-challenge.mydomain.com with the following value:
 
kzVNNLb5zvWxxiW30WbdD54OMYO5gbXRmqmpKPHihmQ
 
Before continuing, verify the record is deployed.
```
